### ISSUE TITLE
Eine README

### ISSUE THREAD

**Issue by slekrem** [slekrem/github-issue#2]
**Links:**
- [Eine README](https://help.github.com/articles/create-a-repo/#commit-your-first-change)
- [README template](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)

**Tasks:**
- [ ] Was macht dieses Projekt?
- [ ] Wozu nützt es?
- [ ] Wie kann ich anfangen, es zu nutzen oder etwas beizutragen?
- [ ] Wo wird mir geholfen, wenn ich Hilfe benötige?
